version: "3"

tasks:
    run: 
        desc: Run the app
        cmds:
        - go run .

    build:
        desc: Build the app
        cmds:
        - go build -ldflags "-s -w -X main.version=x.x.x" -o bin/kubekumber .

    clean:
        desc: Clean up the app
        cmds:
        - rm -rf dist 